spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/presalesdb
    username: presalesadmin
    password: presalesadmin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
logging:
  level:
    com.sedin.presales: DEBUG
    org.springframework.security: DEBUG
